feat(*): define the schema subject as topicName.schemaNema
Flaxoos/extra-ktor-plugins pull request #33
Opened 2024-06-14 01:39 UTC by diegopatinor

https://github.com/Flaxoos/extra-ktor-plugins/issues/32

2024-06-18 10:17 UTC, Flaxoos requested changes
Thanks for this. Do you mind adding a test for this?

2024-06-21 19:38 UTC, diegopatinor commented
> @diegopatinor Thanks for this. Do you mind adding a test for this?

Hi, ok, I'll add it

2024-06-21 22:22 UTC, diegopatinor commented
Added and working.

![image](https://github.com/Flaxoos/extra-ktor-plugins/assets/63062347/f36eeaad-ba06-4cf5-8ed5-9348db3e429e)

2024-06-27 07:28 UTC, Flaxoos approved these changes

2024-06-27 07:29 UTC, merged